/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'description' : IDL.Text,
  'ctaUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'ctaLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getFeaturedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'description' : IDL.Text,
    'ctaUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'ctaLabel' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getFeaturedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };